name: conciergerie-whatsapp-ai
region: fra

services:
  - name: backend
    source_dir: backend
    github:
      repo: Anthopululu/conciergerie-whatsapp-ai
      branch: main
    run_command: node dist/server.js
    build_command: npm install && npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: TWILIO_ACCOUNT_SID
        scope: RUN_TIME
        type: SECRET
      - key: TWILIO_AUTH_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ADMIN_PASSWORD
        scope: RUN_TIME
        type: SECRET

static_sites:
  - name: frontend
    source_dir: frontend
    github:
      repo: Anthopululu/conciergerie-whatsapp-ai
      branch: main
    build_command: npm install && npm run build
    output_dir: dist
    routes:
      - path: /app

  - name: frontend-admin
    source_dir: frontend-admin
    github:
      repo: Anthopululu/conciergerie-whatsapp-ai
      branch: main
    build_command: npm install && npm run build
    output_dir: dist
    routes:
      - path: /admin

